#!/usr/bin/env bash
# Script that transfers a file from client to server

# Check if less than 4 parameters are passed
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters
FILE=$1
IP=$2
USER=$3
KEY=$4

# Transfer the file to the remote user's home directory using scp
scp -o StrictHostKeyChecking=no -i "$KEY" "$FILE" "$USER@$IP:~/"

