#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page (301 Moved Permanently)

# Update and install nginx
apt-get update -y
apt-get install -y nginx

# Start nginx (without systemctl)
service nginx start

# Create a simple homepage
echo "Holberton School" > /var/www/html/index.html

# Configure redirection in default
cat > /etc/nginx/sites-available/default << 'EOF'

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files $uri $uri/ =404;

    }
}
EOF

# Restart nginx to apply configuration
service nginx reload

